### ISSUE TITLE
random.org 403'ing and sends back a captcha

### ISSUE THREAD

**Issue by leroix** [dlom/node-random#2]
This is now happening with this module, but it doesn't happen with `curl`. I think random.org has precautionary filters in place on the old api to ensure it's being used by humans now that they have their json-rpc api.

**Comment by dlom** [comment]
Seems to be an issue with cloudflare and request.js.  I'll look into it.

**Comment by dlom** [comment]
Should be fixed, let me know if you run into any more issues
